language: node_js

git:
  depth: 3

stages:
  - deploy

jobs:
  include:
    - stage: deploy
      name: "Deploy to gh-pages"
      if: branch = master
      script:
        - npm run deploy
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GH_TOKEN
        keep-history: true
        local-dir: gh-pages
        on:
          branch: master