language: node_js

git:
  depth: 3

stages:
  - deploy

jobs:
  include:
    - stage: deploy
      name: "Deploy to gh-pages"
      if: branch = master
      script:
        - git clone --depth=1 --branch=gh-pages https://github.com/w3c/aria-at.git
        - cd aria-at
        - npm install
        - npm run build
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GH_TOKEN
        keep-history: true
        local-dir: dist
        on:
          branch: master